import type { Metadata } from "next";
//import { Inter } from 'next/font/google'
import "./globals.css";
import Providers from "@/store/Provider";
//const inter = Inter({ subsets: ['latin'] })
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
        <Toaster position="bottom-center" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
